# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'react_native_firebase_fcm_example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react_native_firebase_fcm_example
  pod 'Firebase/Core'

end